import Head from "next/head";
import Link from "next/link";
import Layout from "../components/Layout";
export default function Home() {
  return (
    <>
      <Layout>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link
            rel="preconnect"
            href="https://fonts.gstatic.com"
            crossorigin=""
          />
          <link
            href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700;800;900&amp;display=swap"
            rel="stylesheet"
          />

          <link
            rel="stylesheet"
            href="https://unicons.iconscout.com/release/v4.0.0/css/line.css"
          />
          <link
            href="assets/css/theme-rtl.min.css"
            type="text/css"
            rel="stylesheet"
            id="style-rtl"
          />
          <link
            href="assets/css/theme.min.css"
            type="text/css"
            rel="stylesheet"
            id="style-default"
          />
          <link
            href="assets/css/user-rtl.min.css"
            type="text/css"
            rel="stylesheet"
            id="user-style-rtl"
          />
          <link
            href="assets/css/user.min.css"
            type="text/css"
            rel="stylesheet"
            id="user-style-default"
          />
        </Head>

        <h1 style={{textAlign:"center"}}>home page </h1>
      </Layout>
    </>
  );
}
