import Head from "next/head";
import Link from "next/link";
import ListPosts from "@/components/Posts/ListPosts";
import Layout from "@/components/Layout";
import Footer from "@/components/Footer";
import withAuth from '../auth/withAuth';




 function Home() {
 
  return (
    <>
      <Layout>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link
            rel="preconnect"
            href="https://fonts.gstatic.com"
            crossorigin=""
          />
          <link
            href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700;800;900&amp;display=swap"
            rel="stylesheet"
          />

          <link
            rel="stylesheet"
            href="https://unicons.iconscout.com/release/v4.0.0/css/line.css"
          />
          <link
            href="assets/css/theme-rtl.min.css"
            type="text/css"
            rel="stylesheet"
            id="style-rtl"
          />
          <link
            href="assets/css/theme.min.css"
            type="text/css"
            rel="stylesheet"
            id="style-default"
          />
          <link
            href="assets/css/user-rtl.min.css"
            type="text/css"
            rel="stylesheet"
            id="user-style-rtl"
          />
          <link
            href="assets/css/user.min.css"
            type="text/css"
            rel="stylesheet"
            id="user-style-default"
          />
        </Head>

        <div style={{ marginRight: 0 }} class="content ">
          <div class="pb-9">
            <div class="row gy-3 gx-5 gx-xxl-6">
              <div class="col-12">
                <div class="mb-9">
                  <ListPosts />
                </div>
                <div class="text-center">
                  <a class="btn btn-link fs-0 p-0" href="#!">
                    Load more
                  </a>
                </div>
              </div>
            </div>
          </div>
          <Footer />
        </div>
      </Layout>
    </>
  );
}
export default withAuth(Home);